---
- name: Insert Error Message Info into MySQL DB
  hosts: all
  become: yes
  vars:
    db_host: "localhost"
    db_user: "mysql"
    db_pass: "redhat"
    db_name: "aiopsdb"
    # This will be dynamically templated during playbook execution
    sql_template: >
        SELECT * from Error_Table;
    
  tasks:
    - name: Ensure MySQL client is installed
      ansible.builtin.package:
        name: mysql
        state: present

    - name: Insert entry into MySQL database
      ansible.builtin.shell: |
        mysql -h {{ db_host }} -u {{ db_user }} -p'{{ db_pass }}' {{ db_name }} -e "{{ sql_template }}"
