---
- name: Install and configure Apache web server on RHEL
  hosts: all
  become: yes
  vars:
    apache_packages:
      - httpd
    apache_service: httpd
    web_root: /var/www/html
    index_file: index.html
    index_content: "<html><body><h1>Welcome to Apache on RHEL!</h1></body></html>"

  tasks:
    - name: Install Apache packages
      yum:
        name: "{{ apache_packages }}"
        state: present

    - name: Ensure Apache is enabled and started
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true

    - name: Create index.html with a welcome message
      copy:
        dest: "{{ web_root }}/{{ index_file }}"
        content: "{{ index_content }}"
        owner: apache
        group: apache
        mode: '0644'

    - name: Open HTTP port in the firewall (if firewalld is used)
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_facts['os_family'] == "RedHat"
