---
- name: Check status
  hosts: all
  sources:
    - name: URL to check
      ansible.eda.url_check:
        urls:
          - http://10.64.64.190

  rules:
    - name: Insert Error Message Info into MySQL DB
      condition: event.status == "down"
      action:
        run_playbook:
          name: ../insert_error_message.yml
