---
- name: Check status
  hosts: all
  sources:
    - name: URL to check
      ansible.eda.url_check:
        urls:
          - http://10.64.64.190
 
  rules:
    - name: Print output of event.payload
      condition: event.url is defined
      action:
        run_module:
          name: ansible.builtin.debug
          module_args:
            msg: "{{ event.url }}"
