---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Heard "Hello!"
      condition: event.payload.message == "Hello!"
      action:
        debug:
          msg: "You said, '{{ event.payload.message }}'"
          
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool"
      action:
        run_job_template:
          name: "WebServer Restart"
          organization: "Default"
 
